grpc:
  server_port: 50051
  client_address: "localhost:50051"

database:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  dbname: "toolstenancy"
  sslmode: "disable"

rabbitmq:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"
  queue: "user-queue"

logging:
  level: "info"
  format: "json"